### PR TITLE
Sim For real this time

### PR DESCRIPTION
**Pull request by DewsDavid31**
Now all changes are added, let's go again, may need manual merging.

### CODE REVIEW

**Comment by MXHJohn314** [comment]
squash and merge

**Review by MXHJohn314 — COMMENTED** [review]
looks good

**Review by dbowling21 — APPROVED** [review]
Looks like this can merge with frontend

**Review by hdelgad3 — APPROVED** [review]
Fine work!.?:;

**Review by MXHJohn314 — APPROVED** [review]

**Review by robo-jones — APPROVED** [review]

**Pull request merged**
