### PR TITLE
Solution Refactor

### PR DESCRIPTION
**Pull request by MXHJohn314**
- Heavy refactor of folder sturcture with projects split between two "solution folders"
  + ImplementationExample (solution folder)
    + SimDrone
  + OpenDroneDispatchApi (solution folder)
    + Dispatch
    + Domain
      + DTO
        + DroneDispatchCommunication
        + FrondEndDispatchCommunication
      + Entities
      + InterfaceDefinitions
        + Gateways
        + Repositories
      + InterfaceImplementations
        + Gateways
        + Repositories
    + FrontEnd (no folder structure changes)
    + Tests (no folder structure changes)
- Added Docker support for containerizing `SimDrone` and `Dispatch`
- Added Swagger support for `SimDrone` and `Dispatch`
- Created DTOs  for all communications through gateways, which all inherit from `BaseDTO`, implement giving them an implementation of `IJsonifiable` (ensuring that all DTO objects can be turned into a proper JSON string)
- All `Domain.Entities` objects have proper Bson representations for MongoDB mapping
- Using `MongoDB.Driver` to implement `IOrdersRepository` as `OrderRepository` and `IDronesRepository` as `FleetRepository`
- Added `FrontEndToDispatchGateway` for communication with containerized `Dispatch` project
- Reimplemented `Drone.DeliverOrder()` such that the divide by zero exception is avoided.
- Added a line to `OrderPages.Razor.cs` to add an order with the new gateway and added  the associated `FrontEndToDispatchGateway` service to `FrontEnd.Services`

### CODE REVIEW

**Review by robo-jones — APPROVED** [review]

**Review by DewsDavid31 — APPROVED** [review]
Stable, will fix tests in a bit

**Comment by KamronCorreia1** [comment]
looks good to me

**Review by KamronCorreia1 — COMMENTED** [review]
Looks correct

**Review by KamronCorreia1 — APPROVED** [review]

**Comment by MXHJohn314** [comment]
Merging now

**Pull request merged**
